/*
 * This source file was generated by the Gradle 'init' task
 */
package bootcamp;
// import java.util.Scanner;

public class App {
    public static String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        // Scanner scanner = new Scanner(System.in);
        System.out.println("Quanto é 2 + 2?");

        System.out.printf("O resutaldo é 4 \n");
    }
}
